# HollowOS keyboard module config
---
convertedKeymapPath: "/lib/kbd/keymaps/xkb"

# Write keyboard config to these locations
writeEtcDefaultKeyboard: true
writeEtcDefaultKeyboard: true

# Default layout shown in installer
defaultLayout:  "us"
defaultVariant: ""
