# HollowOS network check module
# Uses our custom QML page instead of Calamares default

---

# Point to our custom QML page
qmlFilename: "NetworkCheck.qml"

# Check this URL to determine connectivity
url: "https://voidlinux.org"

# How often to recheck in milliseconds
checkIntervalMs: 3000
