# HollowOS Calamares settings.conf
# Controls the installer module sequence and behaviour

---

modules-search: [ local, /usr/lib/calamares/modules ]

sequence:
  - show:
    - welcome
    - networkcfg
    - locale
    - keyboard
    - DEPicker
    - HardwareScan
    - Software
    - partition
    - users
    - summary
    - install
    - finished

  - exec:
    - partition
    - mount
    - unpackfs
    - machineid
    - fstab
    - locale
    - keyboard
    - localecfg
    - users
    - displaymanager
    - networkcfg
    - hwclock
    - services-systemd
    - packages
    - shellprocess-limine
    - hollow-generate
    - umount

branding: hollowos

prompt-install: true

dont-chroot: false

oem-setup: false

disable-cancel: false

disable-cancel-during-exec: true
