---
modules-search: [ local, /usr/lib/calamares/modules ]

sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - users
    - summary

  - exec:
    - mount
    - unpackfs
    - fstab
    - locale
    - keyboard
    - users
    - umount

branding: hollowos
prompt-install: true
dont-chroot: false
disable-cancel: false
disable-cancel-during-exec: true
