---
modules-search: [ local, /usr/lib/calamares/modules, /usr/lib64/calamares/modules ]

sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - DEPicker
    - HardwareScan
    - Software
    - users
    - summary

  - exec:
    - mount
    - unpackfs
    - fstab
    - locale
    - keyboard
    - localecfg
    - networkcfg
    - hwclock
    - users
    - shellprocess@shellprocess-hollow
    - umount

branding: hollowos
prompt-install: true
dont-chroot: false
disable-cancel: false
disable-cancel-during-exec: true
